---
- name: learning about block and rescue
  hosts: planetexpress
  gather_facts: yes

  tasks:
          - name: Pre-check block
            block:
                    - name: prececk step1
                      shell: "echo 'precheck step1' >> example.txt"

                    - name: prececk step2
                      shell: "echo 'precheck step2' >> example.txt"

                    - name: a real example of a prececk step
                      fail:
                              msg: "Precheck FAILED!"
                      when: ansible_os_family != "Debian"
            rescue:
                    - name: Precheck failed
                      fail:
                              msg: "Precheck failed for {{ inventory_hostname }}! Nothing to roll back. Exiting...."
          - name: Maintenance block
            block:
                    - name: maintenance step1
                      shell: "echo 'maintenace step 3' >> example.txt"

                    - name: maintenace step2
                      shell: "/bin/false"

            rescue:
                    - name: back out maintenance step1
                      lineinfile:
                              path: example.txt
                              state: absent
                              line: "mainteneace step 3" 

                    - name: fail out of playbook
                      fail:
                              msg: "Maintenace block FAILED  Rollback completed. Exiting"

