---
- name: Using ansible to call python code
  gather_facts: yes
  hosts: localhost

  tasks:
          - name: call my python scripts
            script: ~/ans/scripts/parselog.py
            args:
              executable: python3
            register: results

            #     - debug:
            #     var: results.stdout

          - name: load my yaml file that was just created
            include_vars:
                    name: ips
                    file: ~/ans/files/parsed.ips

          - debug:
                  var: ips
