---
- name: Intro to looping
  hosts: localhost
  gather_facts: no

  vars: # vars available to all tasks
    ethList:
      - eth0
      - eth1
      - eth2
      - eth3

  tasks:

    - name: Demo a tiny loop
      debug:
        # item is always the var mapped to loop
        msg: "The debug module allows us to display to the screen: {{ item }}"
      loop: "{{ ethList }}"

    - name: cast local vars into loop
      debug:
              var: item

      loop:
              - 192.168.70.1
              - 10.10.0.1
